### ISSUE TITLE
About VIDL and the scalar IR to Pattern Matcher?

### ISSUE THREAD

**Issue by wjfjfm** [ychen306/vegen#37]
I'm interested by the 4.1 Vector Instruction Description Language / 4.2 Generating Pattern Matchers / 4.3 Pattern Matching of the Pater.
But I can't find the example VIDL description and how it generates a self-defined instructions' Pattern Matcher in is repo.
Could you give me some information about: is this part open sourced and where to find them?

**Comment by ychen306** [comment]
VIDL is defined [here](https://github.com/ychen306/vegen/blob/rerewrite/sema/ir.py). It might be helpful to see how it's used in the script [script](https://github.com/ychen306/vegen/blob/rerewrite/sema/lift_sema.py#L454) we use to generate VIDL from z3 semantics. We generate the pattern matcher from VIDL in this [file](https://github.com/ychen306/vegen/blob/rerewrite/sema/gen_rules.py)

**Comment by wjfjfm** [comment]
Thanks!
