### ISSUE TITLE
"Option 'filter' registered more than once!"

### ISSUE THREAD

**Issue by wjfjfm** [ychen306/vegen#39]
Sorry for, after build succesfully, there is a runtime error when compiling a simple program. It says "Option 'filter' registered more than once!". I can't figure out what wrong so looking for help...

```
+ vegen-clang++ gcc_loops.cpp -o gcc_loops.vegen.bin
: CommandLine Error: Option 'filter' registered more than once!
fatal error: error in backend: inconsistency in registered CommandLine options
clang-12: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Homebrew clang version 12.0.1
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm@12/12.0.1_1/bin
clang-12: note: diagnostic msg: Error generating preprocessed source(s).
```

**Comment by wjfjfm** [comment]
finally this is another ABI compatbility problem.
Here, it is using default `clang` which may different from the clang defined by LLVM_DIR.
```
add_custom_command(OUTPUT ${ARM_WRAPPERS}
  COMMAND clang -D__MM_MALLOC_H -target aarch64-unknown-linux-gnu -O3 -emit-llvm ${ARM_FLAGS} ${CMAKE_CURRENT_SOURCE_DIR}/target-wrappers/arm.c -c -Wno-argument-outside-range -o
${ARM_WRAPPERS}
  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/target-wrappers/arm.c
  VERBATIM
)
```

**Comment by ychen306** [comment]
We've only tested this against llvm-12, and the problem is that llvm-12.01 introduced a flag whose name clashes with ours. To fix that you can rename the `filter` flag to something else (we plan on upgrading later) https://github.com/ychen306/vegen/blob/rerewrite/gslp/GSLP.cpp#L60-L62

**Comment by wjfjfm** [comment]
Thanks! finally run it successfully, after renamed the filter option.
