### ISSUE TITLE
No module named 'bit_util' in fuzzer.py

### ISSUE THREAD

**Issue by ckf104** [ychen306/vegen#41]
Hello, I am trying to regenerate intermediate file `/sema/x86/intrinsics.all.sema` and guess that it may be generated from `sema-gen.py`. But when I try to run, python shows that `No module named bit_util in fuzzer.py`. I can't find this module in PyPI. May any helper python file isn't uploaded ?

**Comment by ychen306** [comment]
I forgot to track that file. Just pushed.
