### ISSUE TITLE
test failed in ispc/c-test-108.c

### ISSUE THREAD

**Issue by ckf104** [ychen306/vegen#42]
I try to run `lit .` in `build/test` directory to test, but  `c-test-108.c` test failed because defenition of `sqrtf` is not found. Should the math library be linked here ?
```c
// RUN: %clang-o3 -march=native -mllvm -filter=kernel %s -o %t && %t
````

**Comment by ychen306** [comment]
Yeah. You will need `-lm`. I only used those tests on my mac, which doesn't require the flag.

**Comment by ckf104** [comment]
By the way, are only tests in `test/vectorize` directory used to check vectorization? I found that most tests pass just because they can run successfully without checking whether some vector IR exist.

**Comment by ychen306** [comment]
correct.
